#!/bin/bash

python src/model/train.py \
    --data_dir ./data_test/text_recognizer_data/ \
    --checkpoint_dir ./checkpoints_ctc \
    --tensorboard_dir ./runs_ctc \
    --img_height 224 \
    --img_width 224 \
    --patch_size 8 \
    --embedding_dim 256 \
    --num_heads 8 \
    --num_layers 6 \
    --mlp_dim 512 \
    --hidden_classifier 512 \
    --num_classes 27 \
    --dropout 0.1 \
    --batch_size 4 \
    --num_epochs 100 \
    --lr 1e-4 \
    --weight_decay 1e-5 \
    --gradient_clip 5.0 \
    --loss_weights 0.5 0.3 0.2 \
    --focal_alpha 1.0 \
    --focal_gamma 2.0 \
    --label_smoothing 0.1 \
    --use_ctc \
    --ctc_blank 26 \
    --use_scheduler \
    --scheduler_type plateau \
    --early_stopping_patience 15 \
    --use_tensorboard \
    --save_every 5 \
    --num_workers 4 \
    --device cuda
